default:
    development:   true
    disableCaches: false

    tests:
        - ["{hostname}", "(a-z).scabbiafw.com|scabbiafw.com"]

    namespaces:
        App: "{app}"

    environments:
        http: "Scabbia\\Environments\\Http"
        cli:  "Scabbia\\Environments\\Cli"

    modules:
        front:  "App\\FrontModule"
        admin:  "Scabbia\\Modules\\PanelModule"
