default:
    development:   true
    disableCaches: false

    type: "Scabbia\\Mvc\\Application"

    tests:
        # - ["{host}", "/(a-z).scabbiafw.com|scabbiafw.com/"]
        # - ["{os}", "/win.*/"]

    sources:
        - "{basepath}/src/"

    # events:
    #     preenvironment:
    #         - "MyProject\\Project::autoexec"

    modules:
        front:
            namespace: "MyProject\\FrontModule"
            fancyName: "Base Module"

        front2:
            namespace: "MyProject\\FrontModule"
            fancyName: "Spare Module"

        admin:
            namespace: "Scabbia\\Modules\\PanelModule"
