default:
    development:   true
    disableCaches: false

    type: "Scabbia\\Mvc\\MvcApplication"

    tests:
        # - ["{host}", "/(a-z).scabbiafw.com|scabbiafw.com/"]
        - ["{os}", "/win.*/"]

    sources:
        - "{basepath}/src/"

    # autoexec:
    #     - "MyProject\\Project::autoexec"

    environments:
        http: "Scabbia\\Environments\\Http"
        cli:  "Scabbia\\Environments\\Cli"

    modules:
        front:  "MyProject\\FrontModule"
        admin:  "Scabbia\\Modules\\PanelModule"
