default:
    development:   true
    disableCaches: false

    type: "Scabbia\\Mvc\\Application"

    tests:
        # - ["{host}", "/(a-z).scabbiafw.com|scabbiafw.com/"]
        - ["{os}", "/win.*/"]

    sources:
        - "{basepath}/src/"

    # events:
    #     preenvironment:
    #         - "MyProject\\Project::autoexec"

    modules:
        front:  "MyProject\\FrontModule"
        admin:  "Scabbia\\Modules\\PanelModule"
