#!/usr/bin/env php
<?php
/**
 * Scabbia2 PHP Framework Skeleton Project
 * http://www.scabbiafw.com/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @link        http://github.com/scabbiafw/scabbia2-skel for the canonical source repository
 * @copyright   2010-2013 Scabbia Framework Organization. (http://www.scabbiafw.com/)
 * @license     http://www.apache.org/licenses/LICENSE-2.0 - Apache License, Version 2.0
 */

// MD # console initialization
if (PHP_SAPI !== "cli") {
    throw new RuntimeException("scabbia only runs under Command Line Interface (CLI).");
}

if (count($_SERVER["argv"]) <= 1) {
    throw new RuntimeException("scabbia needs a command to run.");
}

$tCommands = array_slice($_SERVER["argv"], 1);

if (trim($tCommands[0]) === "upgrade") {
    $tPhpCmd = "php -dsafe_mode=0";

    if (!file_exists("composer.phar")) {
        passthru($tPhpCmd . " -r \"eval('?' . '>' . file_get_contents('https://getcomposer.org/installer'));\"");
	}

	$tComposerCmd = $tPhpCmd . " composer.phar";

	if (file_exists("vendor")) {
		passthru($tComposerCmd . " update");
	} else {
		passthru($tComposerCmd . " install");
	}

    exit;
}

// MD # composer initialization
// MD - determine running path
$tRunningPath = __DIR__;

// MD - determine running path
if (!file_exists($composerAutoloaderPath = "{$tRunningPath}/vendor/autoload.php")) {
    throw new \RuntimeException("Unable to load Composer which is required for Scabbia2. Run `php scabbia upgrade`.");
}

// MD - load the autoloader
$composerAutoloader = require($composerAutoloaderPath);

// MD - set framework path if necessary
// define("SCABBIA2_PATH", "{$tRunningPath}/../scabbia2-fw");
if (defined("SCABBIA2_PATH")) {
    $composerAutoloader->setPsr4("Scabbia\\", SCABBIA2_PATH . "/src/");
    $composerAutoloader->setPsr4("Scabbia\\Tests\\", SCABBIA2_PATH . "/tests/");
}

// MD # framework initialization
// TODO Instead of "Commands" static class, a console application can be created
use Scabbia\Framework\Core;
use Scabbia\Commands\Commands;

// MD - initializes the autoloader and framework variables.
Core::init($composerAutoloader);

// MD - read the command definitions from commands.yml file and cache its content into cache/commands.yml.php
Commands::load("commands.yml");

// MD - execute which command is going to run
$tExitCode = Commands::execute($tCommands);
exit($tExitCode);
